### ISSUE TITLE
Correção de URL do Patreon

### ISSUE THREAD

**Issue by vitormattos** [LibreCodeCoop/site#227]
Não temos um Patreon para a LibreCode, só para o LibreSign.

Como está no site:

https://github.com/LibreCodeCoop/site/blob/main/source/index.blade.php#L151

Como deveria ser:

https://www.patreon.com/libresign

Talvez seja até bom remover o Patreon para focarmos no GitHub Sponsors. O que acha @DaianeAlvesRJ ?

**Comment by ferox** [comment]
@vitormattos Acho devemos remover o Patreon e adicionar outras plataformas como Benfeitoria.
